# Generated by Django 4.0.4 on 2022-07-04 04:03

import books.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['volume_no', 'page_no', 'type']},
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='scanned_text',
            field=models.TextField(blank=True, help_text='Scanned version of the page.', max_length=100, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=10240000)]),
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='typed_text',
            field=models.TextField(blank=True, help_text='Typed version of the page.', max_length=100, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=1024000)]),
        ),
        migrations.AlterField(
            model_name='page',
            name='scanned_text',
            field=models.FileField(blank=True, help_text='Scanned version of the page.', upload_to=books.models.media_directory_path, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=10240000)]),
        ),
        migrations.AlterField(
            model_name='page',
            name='typed_text',
            field=models.FileField(blank=True, help_text='Typed version of the page.', upload_to=books.models.media_directory_path, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=1024000)]),
        ),
    ]
